CREATE TABLE Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
	UserName VARCHAR(100),
    Email VARCHAR(100) UNIQUE,
    UserPassword VARCHAR(255)
);
CREATE TABLE MOVIE(
MovieID INT AUTO_INCREMENT PRIMARY KEY,
MovieName VARCHAR(50),
PosterURL VARCHAR(255),
MovieDuration INT
)